### ISSUE TITLE
Support multi checkbox group

### ISSUE THREAD

**Issue by brunolemos** [fregante/webext-options-sync#13]
```
<input type="checkbox" name="enabled_features[]" value="featureA" checked />Feature A<br />
<input type="checkbox" name="enabled_features[]" value="featureB" />Feature B<br />
<input type="checkbox" name="enabled_features[]" value="featureC" />Feature C<br />
```

### Expected Result

```json
{
  "enabledFeatures": ["featureA"]
}
```

or

```json
{
  "enabledFeatures": {
    "featureA": true,
    "featureB": false,
    "featureC": false
  }
}
```

### Current Result

```json
{
  "enabledFeatures[]": true
}
```

This is common at least when I was in the php world a few years ago:
https://gist.github.com/southern-hu/5424068
http://www.wastedpotential.com/html-multi-checkbox-set-the-correct-way-to-group-checkboxes/

**Comment by bfred-it** [comment]
That sounds like a good idea. PR welcome to implement it as an array:

```json
{
  "enabledFeatures": ["featureA"]
}
```

**Comment by AndersDJohnson** [comment]
We could consider using something like [form-serialize](https://www.npmjs.com/package/form-serialize).

**Comment by bfred-it** [comment]
That's not a terrible idea, it would free `webext-options-sync` from doing any form parsing, however we still need an `unserialize` version to apply the data back to the form.

**Comment by AndersDJohnson** [comment]
@bfred-it Good point. Looks like there is a fork of it that supports deserialization ([form-serialization](https://www.npmjs.com/package/form-serialization)), though I found a more widely used one that supports both serialize and deserialize: [dom-form-serializer](https://www.npmjs.com/package/dom-form-serializer).

**Comment by bfred-it** [comment]
Amazing, thanks! Could you send a PR for that?

**Comment by bfred-it** [comment]
A build step is coming in #20 so it will be easier to integrate this.

**Comment by AndersDJohnson** [comment]
@bfred-it Thanks, let me know when that's in?

**Comment by bfred-it** [comment]
It's in!

**Comment by fregante** [comment]
Can you test https://github.com/fregante/webext-options-sync/pull/28 out with:

```sh
npm install webext-options-sync@next
```

You can then verify the stored data with `chrome.storage.sync.get(console.log)`. You'll also see that default's aren't included (except the arrays/object that are now possible thanks to that module)
