### ISSUE TITLE
Optionally use `chrome.storage.local`

### ISSUE THREAD

**Issue by AndersDJohnson** [fregante/webext-options-sync#19]
We could add a feature to optionally use `chrome.storage.local` instead of `chrome.storage.sync`.

**Comment by bfred-it** [comment]
https://github.com/bfred-it/webext-options-sync/pull/8

**Comment by AndersDJohnson** [comment]
What if we prefer to only store options locally rather than sync to the cloud across all user browsers/devices?

**Comment by bfred-it** [comment]
That’s the user’s choice, they can disable the sync

**Comment by karlicoss** [comment]
@fregante by 'disable the sync' you mean global browser sync right? Don't think it's configurable on per-addon basis. I'm working on extension where it might be desirable for user to use different settings across devices, then using `local` makes sense, what do you think?

On the other hand I can implement it through multiple 'settings profiles', all of which are synced and then user chooses one of them, it's just a bit more work (and a potential feature for this library?).

**Comment by fregante** [comment]
I'd rather not offer this option because I think cross-device sync is always preferable from the user's point of view, but I'm willing to add this for extensions with options that are meant to be local (e.g. a port number)

PR welcome, documentation included.

**Comment by adam-lynch** [comment]
Firefox doesn't allow a "temporary addon" (e.g. one loaded via `about:debugging`) to use `sync`;

```
Error: The storage API will not work with a temporary addon ID. Please add an explicit addon ID to your manifest. For more information see https://mzl.la/3lPk1aE
```

You only get an ID once you submit your extension.

I'm going to make a PR to add an option to override `sync` soon;

```javascript
storageApi: chrome.storage.local
```

**Comment by fregante** [comment]
> Firefox doesn't allow a "temporary addon" (e.g. one loaded via `about:debugging`) to use `sync`;

Read the full error message. You only need to specify the add-on ID in the manifest. I use it all the time. 

> I'm going to make a PR to add an option to override `sync` soon;

Thank you! It's best to override it with a string though: `storage: 'local'`

**Comment by adam-lynch** [comment]
>> Firefox doesn't allow a "temporary addon" (e.g. one loaded via about:debugging) to use sync;

>Read the full error message. You only need to specify the add-on ID in the manifest. I use it all the time.

I don't have an add-on ID. The page linked in the error message says I get one when I upload / submit the extension for review;

>Once you have finished developing the extension, you can package it and submit it to AMO for review and signing. If the packaged extension you upload does not contain an ID, AMO will generate one for you. **It's only at this point that the add-on will be assigned a permanent ID**, which will be embedded in the signed packaged extension.

Are you saying I can enter an arbitrary dummy one?

---

>>I'm going to make a PR to add an option to override sync soon;


>Thank you! It's best to override it with a string though: storage: 'local'

I thought of doing that first but accepting an object doesn't cost this package anymore and it is more flexible. It could open the door for solutions to a lot of unforeseen problems / edge cases. Examples I *can* imagine: 

- Maybe someone wants to pass some kind of polyfill / third-party wrapper.
- Maybe they want to pass their own custom object that does some pre-processing and then calls `chrome.storage.sync`. 

But like I said, it's more about leaving the door open.

If you still disagree and really want a string, cool, I'll do it.

**Comment by fregante** [comment]
> I don't have an add-on ID. The page linked in the error message says I get one when I upload / submit the extension for review;

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings


> I thought of doing that first but accepting an object doesn't cost this package anymore and it is more flexible. It could open the door for solutions to a lot of unforeseen problems / edge cases. 

If you manage to make the types work, you can

**Comment by adam-lynch** [comment]
>>I don't have an add-on ID. The page linked in the error message says I get one when I upload / submit the extension for review;

>https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

Ah OK. I won't bother then 👍

**Comment by fregante** [comment]
No interest in over 2 years, closing again.

If you're having trouble in Firefox: [set a gecko.id](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings)
