### ISSUE TITLE
Add export feature

### ISSUE THREAD

**Issue by fregante** [fregante/webext-options-sync#23]
From: https://github.com/sindresorhus/refined-github/issues/2120

This is probably already feasible via:

```js
copy(JSON.stringify(await options.getAll()))

options.setAll(JSON.parse(paste()))
```

However it needs to be easier to use or implement. Either:

- add user-facing globals `window.webextOptionsSync.export/import()` so users can save the config without adding further UI to extensions, or
- add `options.export/import()` methods that save to/from files, so this feature can be implemented as two buttons (i.e. via `<a download>` and `<input type=file>`)

**Comment by sarpik** [comment]
I was about to create an issue, but found this.

I have a similar use case to @evandrocoan's (#2120) - I too use different chrome profiles for different stuff, thus this feature would be highly appreciated.

I like what vscode's setting sync plugin has done (https://github.com/shanalikhan/code-settings-sync) -
they use github gists (either public or private, chosen by the user) to sync the settings of vscode.
I don't know how hard this would be to implement (we probably could extend the scope of the github token to include gists & then work with github's api), but I assume it would provide great UX.

Thanks!

**Comment by fregante** [comment]
Users can already run these, however accessing the right developer tools can be tricky

## Export 
1. Open the extension’s options
2. Open the developer tools _for the extension’s iframe only_
3. Run this to copy the options to your clipboard (it's a compressed string) **and** the command needed to import it
	```js
	copy('browser.storage.sync.set(' + JSON.stringify(await browser.storage.sync.get('options')) + ')')
	```

## Import

1. Open the extension’s options
2. Open the developer tools _for the extension’s iframe only_
3. Paste what you copied and run it
