### ISSUE TITLE
Form values set to `undefined`

### ISSUE THREAD

**Issue by notlmn** [fregante/webext-options-sync#36]
For some fields that (may) always contain default values as defined using the constructor, these fields get set to `undefined` while other fields of the form are being changed.

I was able to reproduce the bug both in Chrome and Firefox for `1.0.0-4`, using https://github.com/sindresorhus/notifier-for-github/pull/189 as test.

| Chrome | Firefox |
| :-: | :-: |
| ![bug-chrome](https://user-images.githubusercontent.com/37769974/62343299-ebfaee00-b507-11e9-81b6-45fe6f4601c8.gif) | ![bug-firefox](https://user-images.githubusercontent.com/37769974/62343304-edc4b180-b507-11e9-9011-0e9d2b0c9135.gif) |

**Comment by fregante** [comment]
Thanks! I'll look into it

**Comment by fregante** [comment]
Found the issue

**Comment by fregante** [comment]
It seems to be all right now in `1.0.0-8`

```js
npm i webext-options-sync@next
```
