### ISSUE TITLE
Sync options to a third party

### ISSUE THREAD

**Issue by fregante** [fregante/webext-options-sync#44]
I was about to create an issue @ https://github.com/sindresorhus/refined-github, but found this.

I have a similar use case to @evandrocoan's (https://github.com/sindresorhus/refined-github/issues/2120) - I too use different chrome profiles for different stuff, thus this feature would be highly appreciated.

I like what vscode's setting sync plugin has done (https://github.com/shanalikhan/code-settings-sync) -
they use github gists (either public or private, chosen by the user) to sync the settings of vscode.
I don't know how hard this would be to implement (we probably could extend the scope of the github token to include gists & then work with github's api), but I assume it would provide great UX.

Thanks!

_Originally posted by @sarpik in https://github.com/fregante/webext-options-sync/issues/23#issuecomment-568515263_

**Comment by fregante** [comment]
A couple of things to note:
- webext-options-sync is not related to GitHub so it knows nothing about the token, it’s just storing a string like others
- the browser already offers syncing across instances so I’m not sure of how useful a third party sync would be, in general

I think the easiest solution would be to enable syncing to a file on your system and let the user sync it or use it as they please. This saves a lot of dev work on syncing implementation since local read/writes are cheap.

I won’t implement this but I’d accept a PR after a discussion on how it should be implemented (API, minimal extension UI to set, change, remove)

**Comment by sarpik** [comment]
Thanks for your input @fregante!

> * webext-options-sync is not related to GitHub so it knows nothing about the token, it’s just storing a string like others

Yeah when I was talking about the github token, I was specifically referencing [refined-github](https://github.com/sindresorhus/refined-github).

> * the browser already offers syncing across instances so I’m not sure of how useful a third party sync would be, in general

yes, the browser does allow syncing once you sign in with your email (at least chrome).

I'm talking about browser profiles with different email accounts singed in.
For example, 1 profile for "work", 1 for "personal projects" and 1 for "casual stuff". In this case, you intentionally log in with different email accounts to have separate tabs, history etc (separation), **but** you still want pretty much the same settings, themes & extensions with the same settings & keybindings etc., and this is the use case I'm talking about.

Unrelated (kinda?), but I'd love to find a "chrome profile manager" app or something that would allow me to create chrome profiles from a template, much like github repos with forking / templating. Sadly, I haven't had any success.
Implementing something like that myself might be cool, but I haven't found information on how to "tinker with" / "hack"  chrome, and it's "User Data Directory" seems hella messy / unreliable to setup a template of some sort. Please lemme know if there's anything like this.

> I think the easiest solution would be to enable syncing to a file on your system and let the user sync it or use it as they please. This saves a lot of dev work on syncing implementation since local read/writes are cheap.

I don't have the expertise to reason about this, sorry:D

Also, should we move this discussion to refined github?

**Comment by fregante** [comment]
No, it won’t happen in RGH unless it’s part of a module already. And even if it is, it’s not guaranteed

**Comment by fregante** [comment]
And now that I think about it, this shouldn’t be part of `webext-options-sync` either. It can be a generic module like

```js
webextSyncToDisk({
  id: `options`,
  get: () => optionsStorage.getAll(),
  set: () => optionsStorage.setAll()
});
``` 

You can make this request on https://github.com/sindresorhus/module-requests
