### ISSUE TITLE
Limits of the suggested setup

### ISSUE THREAD

**Issue by fregante** [fregante/webext-options-sync#5]
Found a solution. Tasks:

- [x] allow definitions to be part of the the constructor, e.g. `new OptionsSync({defaults: {...}})`
- [x] expose `defaults` on the instance
- [ ] update readme to https://github.com/bfred-it/webext-options-sync/issues/5#issuecomment-486559356
- [x] update types to have `.getAll` be a generic and return `typeof defaults`

---

Found them in https://github.com/sindresorhus/hide-files-on-github/pull/61#issuecomment-316666638

- Defaults are only used on the first install and not accessible elsewhere.
- Fields cannot be parsed/changed before saving/retrieving without changing the field.

This would be nice:

```js
const options = new OptionsSync().define({
  defaults: {
    name: "User"
  },
  filters: {
    name: name => `Hello, ${name}`
  }
});

options.defaults.name === "User";
```

The issue is that to enable this, the definition needs to happen in the content script **but** if we do that, we can't access `chrome.runtime.onInstalled`

**Comment by sindresorhus** [comment]
> The issue is that to enable this, the definition needs to happen in the content script

Why does it have to happen in the content script?

**Comment by bfred-it** [comment]
The alternative is to set up messaging to access the definitions in the background script. All set calls would also have to be sent to the background script to see if they need to be filtered.

A simpler solution: we put the defaults in the storage itself, so they can will be accessible anytime anywhere — but then we need another solution for filters. 

Note: I described the wrong type of filter earlier, they should be pre-save filters, not pre-get. I'll fix the example.

**Comment by bfred-it** [comment]
How about this: instead of calling `new OptionsSync()` in every file (definition in `background`, usage in `content`, change in `options`), the user should have a single `options-storage` file that gets included everywhere.

Example:

```js
// options-storage.js
export default new OptionsSync({
  defaults: {
    name: "User"
  },
  filters: {
    name: name => `Hello, ${name}`
  }
});
```
```js
// content or background
import options from './options-storage';

await options.getAll();
```
```js
// options.html
import options from './options-storage';

options.syncForm('#options-form');
```

Or without webpack:

```json
	"background": {
		"scripts": [
			"webext-options-sync.js",
			"options-storage.js",
			"background.js"
		],
		"persistent": false
	},
	"content_scripts": [
		{
			"matches": [
				"https://github.com/*",
			],
			"js": [
				"webext-options-sync.js",
				"options-storage.js",
				"content.js"
			]
		}
```

**Comment by sindresorhus** [comment]
I think that's a good solution. It's how I recommend using `electron-store` too, so people get the same in the main and renderer process for Electron.
