### ISSUE TITLE
Allow post-processing of form data

### ISSUE THREAD

**Issue by aspiers** [fregante/webext-options-sync#61]
IIUC, it seems that data is synced directly from form fields to the options storage via [dom-form-serializer](https://github.com/jefersondaniel/dom-form-serializer).  In some cases it is necessary to post-process form data into a new format before serializing for storage, for example when an individual item exceeds [the 8k size limit](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync-sync-QUOTA_BYTES_PER_ITEM), it is necessary to break it into chunks first before storing.

Is there a recommended way to do this?  If not, would it be possible to add some kind of mechanism to support it?  Thanks!

**Comment by fregante** [comment]
> it is necessary to break it into chunks first before storing



What you're asking makes sense, but I think you can already do it autonomously. `OptionsSync` is a class so you just need to extend it and override the getters and setters since those are what take care of it. Example:

```js
class MyOptionsSync extends OptionsSync {
	async getAll() {
		return myLoadingMechanism()
	}
	async setAll(values) {
		return mySettingMechamism(values)
	}
}
```

**Comment by aspiers** [comment]
Thanks, I'll play with this approach.
