### ISSUE TITLE
Allow using `null` as options values

### ISSUE THREAD

**Issue by karlicoss** [fregante/webext-options-sync#71]
Currently type for `Options` values doesn't include `null` : https://github.com/fregante/webext-options-sync/blob/main/index.ts#L72-L74

```
export interface Options {
	[key: string]: string | number | boolean;
}
```

[Chrome API](https://developer.chrome.com/docs/extensions/reference/api/storage#method-StorageArea-set) isn't explicit whether it allows `null`, but `null` is serializable and deserializable as JSON, so not expecing a problem there:

```
browser.storage.local.set({"an_int": 123, "a_null": null})
Promise { <state>: "pending" }

await browser.storage.local.get()
Object { a_null: null, an_int: 123 }
```

It also works for me as expected with webext-options-sync, I just have to suppress the typescript error.

I find null values can be useful to indicate default/indeterminate values -- would you be open to a PR to allow them? Happy to add tests etc as well.
Thanks!

**Comment by fregante** [comment]
How do you plan on adding that value to the storage? This module exists to sync a form to the storage (hence "sync" in the name), and all fields exclusively return strings and numbers (and booleans for checkboxes)

**Comment by karlicoss** [comment]
Ah I see -- I've been using bare `OptionsSync` object (e.g. `.set`/`.get`/`.exportToFile` etc). 
I think I was planning to use the form sync, but never got round to it, and perhaps when I started using `webext-options-sync` I didn't know of the browser polyfill, so I liked that your library had a proper async API.
Feel free to close!
